server:
   # 随机端口
   port: 0
zuul:
   host: 127.0.0.1
   post: 1111
   
spring:
  jackson:
    date-format: yy-MM-dd HH:mm
    time-zone: GMT+8
  resources:
      staticLocations:
         - classpath:/META-INF/resources/
         - classpath:/resources/
         - classpath:/static/
         - classpath:/public/
         - file:/${upload-dir}
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
    
logging:
   level:
      #root: debug
      com:
         yc: debug
         
upload-dir: d:/hwc_upload/