server:
   port: 1111

zuul:
   # 全局忽略敏感头
   sensitive-headers: 
   routes:
      hwcbook: task/**
      hwcuser: user/**
      hwcindex: /**

spring:
  servlet:
    multipart:
      maxFileSize: 10Mb
      maxRequestSize: 10Mb